# Generated by Django 4.1.2 on 2023-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('image', models.ImageField(upload_to='images/product_module', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(verbose_name='تخفیف')),
                ('quantity', models.IntegerField(max_length=10, verbose_name='تعداد')),
                ('short_description', models.CharField(max_length=150, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(default='', unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
