# Generated by Django 4.1.2 on 2023-01-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_remove_product_description_aboutproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_module.product'),
        ),
    ]
