# Generated by Django 4.1.2 on 2023-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='product',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال شده / نشده'),
        ),
    ]
