# Generated by Django 4.1.2 on 2023-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_imagesproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesproduct',
            options={'verbose_name': 'عکس محصول', 'verbose_name_plural': 'عکس های محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product_module/', verbose_name='تصویر'),
        ),
    ]
