# Generated by Django 4.1.2 on 2023-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
