# Generated by Django 4.1.2 on 2023-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_module', '0002_ads_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', verbose_name='آدرس'),
        ),
    ]
