# Generated by Django 4.1.2 on 2022-12-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های پایین صفحه',
                'verbose_name_plural': 'دسته بندی های لینک های پایین صفحه',
            },
        ),
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سایت')),
                ('site_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='دامنه سایت')),
                ('site_logo', models.ImageField(upload_to='images/site_module/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='ادرس')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='شماره سایت')),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
