# Generated by Django 4.1.2 on 2022-12-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_slider_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLinkBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های سر صفحه',
                'verbose_name_plural': 'دسته بندی های لینک های سر صفحه',
            },
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='site_logo',
            field=models.ImageField(upload_to='images/site_module'),
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkboxes', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک سر صفحه',
                'verbose_name_plural': 'لینک های سر صفحه',
            },
        ),
    ]
