# Generated by Django 4.1.2 on 2022-12-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_headerlinkboxes_alter_site_setting_site_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='footer_link_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_module.headerlinkboxes', verbose_name='دسته بندی'),
        ),
    ]
