# Generated by Django 4.1.2 on 2022-12-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_headerlink_footer_link_box'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderLink',
        ),
    ]
