# Generated by Django 4.1.2 on 2022-12-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_delete_headerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'لینک سر صفحه',
                'verbose_name_plural': 'لینک های سر صفحه',
            },
        ),
        migrations.DeleteModel(
            name='HeaderLinkBoxes',
        ),
    ]
