# Generated by Django 4.1.2 on 2023-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_headerlink_delete_headerlinkboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='url',
            field=models.CharField(max_length=800, verbose_name='لینک'),
        ),
    ]
