# Generated by Django 4.1.2 on 2023-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_alter_headerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
