# Generated by Django 4.1.2 on 2023-03-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_alter_headerlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default='ad', max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
