# Generated by Django 4.1.2 on 2023-01-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/profile.png', null=True, upload_to='images/user_avatar', verbose_name='آواتار'),
        ),
    ]
