# Generated by Django 4.1.2 on 2023-01-19 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده / نشده توسط مدیر')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.comment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ نظر',
                'verbose_name_plural': 'پاسخ های نظر',
            },
        ),
    ]
