# Generated by Django 4.1.2 on 2023-01-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_remove_comment_parent_propertycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.comment', verbose_name='والد'),
        ),
        migrations.DeleteModel(
            name='PropertyComment',
        ),
    ]
