# Generated by Django 4.1.2 on 2023-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_comment_parent_delete_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='درباره کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length='11', null=True, verbose_name='شماره تلفن'),
        ),
    ]
